global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
# Use the following configuration to scrape metrics from a secured endpoints (or use API key)
#    tls_config:
#      cert_file: /path/to/client.crt
#      key_file: /path/to/client.key
#      ca_file: /path/to/ca.crt